name: mappymatch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - geopandas
  - shapely
  - rtree
  - pyproj
  - pandas
  - numpy
  - matplotlib
  - osmnx 
  - networkx
  - folium
  - requests
  - pip
  - pip:
    - -e .
    - sphinxemoji==0.2.0
  - pytest
  - pip-tools
  - sphinx=4.5.0
  - sphinx_rtd_theme=1.0.0
  - sphinxemoji=0.2.0
  - pre-commit
  - black
  - isort
  - interrogate
  - coverage
  - mypy
  - build