# Add dependencies in alphabetical order.
name: mappymatch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - folium
  - geopandas
  - matplotlib
  - numpy
  - osmnx
  - pandas
  - pip
  - pip:
    - -e .
  - pyproj 
  - requests 
  - rtree
  - shapely


