[build-system]
requires = ["setuptools>=63.0.0", "wheel"]
build-backend = "setuptools.build_meta" 


[tool.setuptools.packages.find]
where = ["mappymatch"]

# Ref https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
#[tool.setuptools.package-data]
#include = false
#mappymatch.resources = ["*"]

[project]
name = "mappymatch"
version = "0.2.2"
description = "Package for mapmatching."
readme = "README.md"
authors = [{ name = "National Renewable Energy Laboratory" }]
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: Other/Proprietary License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Topic :: Scientific/Engineering",
]
keywords = ["GPS", "map", "match"]
dependencies = [
    "geopandas",
    "shapely",
    "rtree",
    "pyproj",
    "pandas",
    "numpy",
    "matplotlib",
    "folium",
    "requests",
]
requires-python = ">=3.8"

[project.optional-dependencies]
# Used to run CI. 
tests = [
  "black",
  "isort",
  "mypy",
  "types-requests",
  "flake8",
  "pytest",
]
dev = [
  "pytest",
  "sphinx==4.5.0",
  "sphinx_rtd_theme==1.0.0",
  "sphinxemoji==0.2.0",
  "pre-commit",
  "black",
  "isort",
  "interrogate",
  "coverage",
  "mypy",
  ]
release = [
  "build",
  "twine"
]

[project.urls]
Homepage = "https://github.com/NREL/mappymatch"

[tool.black]
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | env
  | venv
)/
'''
include = '\.pyi?$'
line-length = 79
target-version = ['py38', ]

[tool.isort]
profile = "black"
line_length = 79
skip_gitignore = true
filter_files = true

[tool.interrogate]
fail-under = 10 
exclude = ["tests", "docs", "examples", "resources"]
paths = ["mappymatch"]
# Ignore the docs configuration file.
ignore-regex = ["conf.py"]

[tool.coverage.run]
# Ensures coverage for all if, elif, else branches. 
# https://coverage.readthedocs.io/en/6.3.2/branch.html#branch
branch = true

[tool.coverage.report]
precision = 1
fail_under = 50.0
skip_covered = false
skip_empty = true

