name: Assign-Issue
on:
  issue_comment:
    types: created

jobs:
  issue_assign_job:
    runs-on: ubuntu-latest
    steps: 
    # This job only runs for issue comments.
    - if: github.event.comment.body == 'take' && !github.event.issue.pull_request
      run: |
        echo "Assigning issue ${{ github.event.issue.number }} to ${{ github.event.comment.user.login }}"
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d '{"assignees": ["${{ github.event.comment.user.login }}"]}' https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees
