name: Lint & Type Check 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-tests.txt
    - name: Run black
      run: black mappymatch tests --check
    - name: Run ruff 
      run: ruff mappymatch tests
    - name: Run mypy
      run: mypy mappymatch tests --ignore-missing-imports